export const USER_SERVICE = "USER_SERVICE";
export const AUTH_SERVICE = "AUTH_SERVICE";
export const CATEGORY_SERVICE = "CATEGORY_SERVICE";
export const TICKET_SERVICE = "TICKET_SERVICE";
export const TOKEN_STORAGE_SERVICE = "TOKEN_STORAGE_SERVICE";